### ISSUE TITLE
Project Explanation

### ISSUE THREAD

**Issue by MentalGear** [daniel-amthauer/BMeshUnreal#1]
Would it be possible to better explain the project, e.g. does it provide an interface for runtime manipulation of meshes, if so, what kind of manipulations ?

**Comment by daniel-amthauer** [comment]
Hi, sorry I didn't respond to this in a timely fashion. The personal project that sparked the creation of this plugin was shelved for a while and I recently got back to work on it, and consequently I've also been improving this plugin.

Let me know if the updated explanation for the project seems clear enough!
